# Security Policy

Please do not open public issues for potential security problems.

Send potential security problems to the repository maintainers via GitHub Discussions or create a private security advisory.